const data = {
  postId: 1598201668613,
  userId: 51,
  message:
    'hello @channel, we are making a tweet in #react. thank you for your #support.\n\n\nwe are @sukhiboi and @ragini',
  postedAt: '2020-08-23 22:24:28',
  username: 'sukhiboi',
  githubUsername: 'sukhiboi',
  name: 'Sukhdev',
  bio: 'i am cool',
  dob: '1002-03-12',
  joinedDate: '2020-08-23',
  imageUrl: 'https://avatars3.githubusercontent.com/u/40167376?v=4',
  likedUsers: [
    {
      userId: 51,
      username: 'sukhiboi',
      githubUsername: 'sukhiboi',
      name: 'Sukhdev',
      bio: 'i am cool',
      dob: '1002-03-12',
      joinedDate: '2020-08-23',
      imageUrl: 'https://avatars3.githubusercontent.com/u/40167376?v=4',
    },
  ],
  responseCount: 1,
  repostCount: 0,
  isLiked: true,
  isReposted: false,
  isDeletable: true,
  isBookmarked: false,
  initials: 'S',
  mentions: ['sukhiboi'],
  hashtags: ['react', 'support'],
};
